package common

import "github.com/charmbracelet/lipgloss"

// SectionRowsFn is a callback used by RenderSection to lazily generate
// the rows for a section.
//
// Returning nil or an empty slice indicates that the section has no data
// and will trigger the default "(no data)" placeholder.
type SectionRowsFn func() []string

// RenderSection renders a titled section for a Bubble Tea details panel.
//
// It applies the given headerStyle to the section name, then appends rows
// generated by rowsFn. If rowsFn returns nil or an empty slice, a default
// "(no data)" row is rendered instead.
//
// This helper centralizes section layout concerns (header rendering,
// empty-state handling) while allowing callers to supply domain-specific
// row generation logic.
func RenderSection(
	sectionName string,
	headerStyle lipgloss.Style,
	rowsFn SectionRowsFn,
) []string {

	rows := []string{
		headerStyle.Render(sectionName),
	}

	sectionRows := rowsFn()

	if len(sectionRows) == 0 {
		rows = append(rows, "  (no data)")
		return rows
	}

	for _, r := range sectionRows {
		rows = append(rows, r)
	}

	return rows
}
